# Generated by Django 6.0.3 on 2026-06-24 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('techniciens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_travaux', models.CharField(choices=[('electricite', 'Electricite'), ('plomberie', 'Plomberie'), ('construction', 'Construction'), ('soudure', 'Soudure'), ('peinture', 'Peinture'), ('menuiserie', 'Menuiserie'), ('camera_surveillance', 'camera_surveillance'), ('autre', 'Autre')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('localite', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('urgence', models.CharField(choices=[('normale', 'Normale'), ('urgence', 'Urgence'), ('critique', 'Critique')], default='normale', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('assignee', 'Assignee'), ('en_cours', 'En cours'), ('terminee', 'Terminee'), ('annulee', 'Annulee')], default='en_attente', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='demandes/')),
                ('notes_admin', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_intervention', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL)),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='techniciens.technicien')),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MessageChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu_par_admin', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Chat',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demandes.demande')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
