# Generated by Django 6.0.3 on 2026-06-25 12:08

import pyuploadcare.dj.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
