# Generated by Django 6.0.3 on 2026-04-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0003_alter_demande_id_alter_notification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='urgence',
            field=models.CharField(choices=[('normale', 'Normale'), ('urgence', 'Urgence'), ('critique', 'Critique')], default='normale', max_length=20),
        ),
    ]
